#!/bin/zsh

_DEV_STOP=1
SOURCE=${(%):-%x}
CWD="${0:A:h}"

export FZF_DEBUG=0
FZF_LOGFILE="/tmp/fzf.log"
CACHE_FILE="$CWD/.menu.dat"
FZF_LIB="$CWD/fzf-lib.zsh"

_fzf-assign-vars() {
  local lc=$'\e[' rc=m
  _clr[menu_id]="${lc}${CLR_ID:-38;5;30}${rc}"
  _clr[menu_desc]="${lc}${CLR_DESC:-38;5;8;3}${rc}"

}

_fzf-menu-log() {
  if [[ ! -z ${FZF_LOGFILE} ]]; then
    printf "--------------------\n" >> ${FZF_LOGFILE}
    printf "  %s\n" $* >> ${FZF_LOGFILE}
  fi
}

_fzf-menu-parse-env() {
  while read env_item; do
    env_export="export \"${env_item/: /=}\""
    _fzf-log "setting for $1: \n $env_export"
    eval "$env_export"
  done< <(yq eval '.envs.[]' "$1")
}

# search for .menu.yml files to generate .menu.dat files
_fzf-menu-build-cache() {
  fd_menu="fd --hidden -L -c never --no-ignore --type f \".menu.yml\" $CWD"
  menu_lines=""
  while read menu_file; do
    menu_len=$(yq eval '.actions | length' "$menu_file")
    echo -e "Processing $menu_len items from $menu_file"
    for ((i=0; i<=$menu_len - 1; i++)); do
      id=$(yq eval ".actions.[$i].id" "$menu_file")
      desc=$(yq eval ".actions.[$i].desc" "$menu_file")
      cmd=$(yq eval ".actions.[$i].cmd" "$menu_file")
      cmd_file="$(echo "$cmd" | cut -d' ' -f1)"
      cmd_dir=$(dirname "$menu_file")
      menu_lines="$menu_lines\n|$id|$desc|${cmd_dir}/${cmd_file}"
    done
  done < <(eval "$fd_menu")
  echo -e "$menu_lines" > "$CACHE_FILE"
  echo -e "Wrote $(cat ${CACHE_FILE} | wc -l) items to $CACHE_FILE"
}

_fzf-result() {
  mode="$1" && shift
  selection="$(echo $* | xargs | cut -d' ' -f1)"
  _fzf-log "fzf menu: $selection"
}

_fzf-extra-opts() {
  echo "--with-nth=..-2"
}

_fzf-source() {
  lines=()
  while read -r line; do
    skip_item=0
    id="$(echo "$line" | awk -F'|' '{print $2}')"
    desc="$(echo "$line" | awk -F'|' '{print $3}' | xargs)"
    cmd="$(echo "$line" | awk -F'|' '{print $4}')"

    # if desc field isn't defined assume dynamically generated by _fzf-menu-description
    if [[ "$desc" == "" ]] || [[ "$desc" == "null" ]]; then
      desc="$(eval $(echo $cmd | xargs) --description $(echo $id | xargs))"
      # if exit status was not 0 that signals to not display the menu item
      skip_item=$?
    fi

    if [ $skip_item -ne 0 ]; then
      _fzf-log "menu $id skipped: $skip_item"
    else
      lineout="${_clr[rst]}${_clr[menu_id]}${id}"
      lineout="${lineout}  ${_clr[menu_desc]}${desc}"
      lineout="${lineout}  ${cmd}${_clr[rst]}"
      lines+=( "$lineout" )
    fi
  done < <(cat ${CACHE_FILE} | sort | column -s '|' -o '|' -t)

  printf '%s\n' "${lines[@]}"
}

if [[ $1 == "--cache" ]]; then
  shift && _fzf-menu-build-cache
else
  source "$FZF_LIB"
fi
