#!/usr/bin/env bash

 if [[ -z $1 ]] || [[ $1 == "-" ]]; then
    input=$(mktemp)
    trap "rm -f $input" EXIT
    cat /dev/stdin > $input
else
    input=$1
fi

 # jq '[ .users[] | (.first + " " + .last) ]' ~/test.json

# path logic inspired by https://github.com/stedolan/jq/issues/243
<"$input" yq -C eval '[
    path(..) |
    map(select(type=="string") // "[]") |
    join(".") | split(".[]") | join("[]")
  ] | map("." + .) | unique | .[]' |
fzf \
    --preview "jq --color-output $JQ_REPL_ARGS {q} $input 2>/dev/null" \
    --preview-window="down:90%" \
    --height="99%" \
    --query="." \
    --bind "tab:replace-query,return:print-query" \
    --bind "alt-up:preview-page-up,alt-down:preview-page-down"
