---
envs:
  - FZF_MENU_LOGFILE: "fzf-menu.log"
  - CLR_MENU_ID: "\033[38;5;70m"

actions:
  - id: apt:info
    desc: search and output apt package information
    cmd: apt.zsh --info

  - id: apt:install
    desc: select apt packages to install
    cmd: apt.zsh --install

  - id: apt:remove
    desc: remove installed apt packages
    cmd: apt.zsh --remove

  - id: apt:upgrade
    desc: upgrade apt packages avaiable for update
    cmd: apt.zsh --upgrade
