#!/usr/bin/env bash
ROOTDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

export READER="$ROOTDIR/snippetdb list"

# fuzzy search only on key column
# Filter out the first column ( key ) once selected
export SELECTOR="$ROOTDIR/fzf-common -n 1 | cut -d ' ' -f1"

export FILTER="xargs $ROOTDIR/snippetdb get"

$ROOTDIR/tmux-butler
