
const icons = {
[".babelrc"]: { icon: "ﬥ", color: "#cbcb41", name: "Babelrc", type: 'file' },
[".bashprofile"]: { icon: "", color: "#89e051", name: "BashProfile", type: 'file' },
[".bashrc"]: { icon: "", color: "#89e051", name: "Bashrc", type: 'file' },
[".ds_store"]: { icon: "", color: "#41535b", name: "DsStore", type: 'file' },
[".gitattributes"]: { icon: "", color: "#41535b", name: "GitAttributes", type: 'file' },
[".gitconfig"]: { icon: "", color: "#41535b", name: "GitConfig", type: 'file' },
[".gitignore"]: { icon: "", color: "#41535b", name: "GitIgnore", type: 'file' },
[".gitlab-ci.yml"]: { icon: "", color: "#e24329", name: "GitlabCI", type: 'file' },
[".gitmodules"]: { icon: "", color: "#41535b", name: "GitModules", type: 'file' },
[".gvimrc"]: { icon: "", color: "#019833", name: "Gvimrc", type: 'file' },
[".npmignore"]: { icon: "", color: "#E8274B", name: "NPMIgnore", type: 'file' },
[".settings.json"]: { icon: "", color: "#854CC7", name: "SettingsJson", type: 'file' },
[".vimrc"]: { icon: "", color: "#019833", name: "Vimrc", type: 'file' },
[".zprofile"]: { icon: "", color: "#89e051", name: "Zshprofile", type: 'file' },
[".zshenv"]: { icon: "", color: "#89e051", name: "Zshenv", type: 'file' },
[".zshrc"]: { icon: "", color: "#89e051", name: "Zshrc", type: 'file' },
["CMakeLists.txt"]: { icon: "", color: "#6d8086", name: "CMakeLists", type: 'file' },
["COMMIT_EDITMSG"]: { icon: "", color: "#41535b", name: "GitCommit", type: 'file' },
["COPYING"]: { icon: "", color: "#cbcb41", name: "License", type: 'file' },
["COPYING.LESSER"]: { icon: "", color: "#cbcb41", name: "License", type: 'file' },
["Dockerfile"]: { icon: "", color: "#384d54", name: "Dockerfile", type: 'file' },
["Gemfile$"]: { icon: "", color: "#701516", name: "Gemfile", type: 'file' },
["LICENSE"]: { icon: "", color: "#d0bf41", name: "License", type: 'file' },
["Makefile"]: { icon: "", color: "#6d8086", name: "Makefile", type: 'file' },
["Procfile"]: { icon: "", color: "#a074c4", name: "Procfile", type: 'file' },
["R"]: { icon: "ﳒ", color: "#358a5b", name: "R", type: 'ext' },
["Rakefile"]: { icon: "", color: "#701516", name: "Rakefile", type: 'file' },
["Rmd"]: { icon: "", color: "#519aba", name: "Rmd", type: 'ext' },
["Vagrantfile$"]: { icon: "", color: "#1563FF", name: "Vagrantfile", type: 'file' },
["_gvimrc"]: { icon: "", color: "#019833", name: "Gvimrc", type: 'file' },
["_vimrc"]: { icon: "", color: "#019833", name: "Vimrc", type: 'file' },
["ai"]: { icon: "", color: "#cbcb41", name: "Ai", type: 'ext' },
["awk"]: { icon: "", color: "#4d5a5e", name: "Awk", type: 'ext' },
["bash"]: { icon: "", color: "#89e051", name: "Bash", type: 'ext' },
["bat"]: { icon: "", color: "#C1F12E", name: "Bat", type: 'ext' },
["bmp"]: { icon: "", color: "#a074c4", name: "Bmp", type: 'ext' },
["c"]: { icon: "", color: "#599eff", name: "C", type: 'ext' },
["c++"]: { icon: "", color: "#f34b7d", name: "CPlusPlus", type: 'ext' },
["cc"]: { icon: "", color: "#f34b7d", name: "CPlusPlus", type: 'ext' },
["cfg"]: { icon: "", color: "#ECECEC", name: "Configuration", type: 'ext' },
["clj"]: { icon: "", color: "#8dc149", name: "Clojure", type: 'ext' },
["cljc"]: { icon: "", color: "#8dc149", name: "ClojureC", type: 'ext' },
["cljs"]: { icon: "", color: "#519aba", name: "ClojureJS", type: 'ext' },
["cmake"]: { icon: "", color: "#6d8086", name: "CMake", type: 'ext' },
["coffee"]: { icon: "", color: "#cbcb41", name: "Coffee", type: 'ext' },
["conf"]: { icon: "", color: "#6d8086", name: "Conf", type: 'ext' },
["config.ru"]: { icon: "", color: "#701516", name: "ConfigRu", type: 'file' },
["cp"]: { icon: "", color: "#519aba", name: "Cp", type: 'ext' },
["cpp"]: { icon: "", color: "#519aba", name: "Cpp", type: 'ext' },
["cs"]: { icon: "", color: "#596706", name: "Cs", type: 'ext' },
["csh"]: { icon: "", color: "#4d5a5e", name: "Csh", type: 'ext' },
["cson"]: { icon: "", color: "#cbcb41", name: "Cson", type: 'ext' },
["css"]: { icon: "", color: "#563d7c", name: "Css", type: 'ext' },
["cxx"]: { icon: "", color: "#519aba", name: "Cxx", type: 'ext' },
["d"]: { icon: "", color: "#427819", name: "D", type: 'ext' },
["dart"]: { icon: "", color: "#03589C", name: "Dart", type: 'ext' },
["db"]: { icon: "", color: "#dad8d8", name: "Db", type: 'ext' },
["desktop"]: { icon: "", color: "#563d7c", name: "DesktopEntry", type: 'ext' },
["diff"]: { icon: "", color: "#41535b", name: "Diff", type: 'ext' },
["doc"]: { icon: "", color: "#185abd", name: "Doc", type: 'ext' },
["dropbox"]: { icon: "", color: "#0061FE", name: "Dropbox", type: 'folder' },
["dump"]: { icon: "", color: "#dad8d8", name: "Dump", type: 'ext' },
["edn"]: { icon: "", color: "#519aba", name: "Edn", type: 'ext' },
["eex"]: { icon: "", color: "#a074c4", name: "Eex", type: 'ext' },
["ejs"]: { icon: "", color: "#cbcb41", name: "Ejs", type: 'ext' },
["elm"]: { icon: "", color: "#519aba", name: "Elm", type: 'ext' },
["erb"]: { icon: "", color: "#701516", name: "Erb", type: 'ext' },
["erl"]: { icon: "", color: "#B83998", name: "Erl", type: 'ext' },
["ex"]: { icon: "", color: "#a074c4", name: "Ex", type: 'ext' },
["exs"]: { icon: "", color: "#a074c4", name: "Exs", type: 'ext' },
["f#"]: { icon: "", color: "#519aba", name: "Fsharp", type: 'ext' },
["favicon.ico"]: { icon: "", color: "#cbcb41", name: "Favicon", type: 'file' },
["fish"]: { icon: "", color: "#4d5a5e", name: "Fish", type: 'ext' },
["fs"]: { icon: "", color: "#519aba", name: "Fs", type: 'ext' },
["fsi"]: { icon: "", color: "#519aba", name: "Fsi", type: 'ext' },
["fsscript"]: { icon: "", color: "#519aba", name: "Fsscript", type: 'ext' },
["fsx"]: { icon: "", color: "#519aba", name: "Fsx", type: 'ext' },
["gd"]: { icon: "", color: "#6d8086", name: "GDScript", type: 'ext' },
["gemspec"]: { icon: "", color: "#701516", name: "Gemspec", type: 'ext' },
["gif"]: { icon: "", color: "#a074c4", name: "Gif", type: 'ext' },
["git"]: { icon: "", color: "#F14C28", name: "GitLogo", type: 'folder' },
["glb"]: { icon: "", color: "#FFB13B", name: "BinaryGLTF", type: 'ext' },
["go"]: { icon: "", color: "#519aba", name: "Go", type: 'ext' },
["godot"]: { icon: "", color: "#6d8086", name: "GodotProject", type: 'ext' },
["gruntfile"]: { icon: "", color: "#e37933", name: "Gruntfile", type: 'file' },
["gulpfile"]: { icon: "", color: "#cc3e44", name: "Gulpfile", type: 'file' },
["h"]: { icon: "", color: "#a074c4", name: "H", type: 'ext' },
["haml"]: { icon: "", color: "#eaeae1", name: "Haml", type: 'ext' },
["hbs"]: { icon: "", color: "#f0772b", name: "Hbs", type: 'ext' },
["hh"]: { icon: "", color: "#a074c4", name: "Hh", type: 'ext' },
["hpp"]: { icon: "", color: "#a074c4", name: "Hpp", type: 'ext' },
["hrl"]: { icon: "", color: "#B83998", name: "Hrl", type: 'ext' },
["hs"]: { icon: "", color: "#a074c4", name: "Hs", type: 'ext' },
["htm"]: { icon: "", color: "#e34c26", name: "Htm", type: 'ext' },
["html"]: { icon: "", color: "#e34c26", name: "Html", type: 'ext' },
["hxx"]: { icon: "", color: "#a074c4", name: "Hxx", type: 'ext' },
["ico"]: { icon: "", color: "#cbcb41", name: "Ico", type: 'ext' },
["import"]: { icon: "", color: "#ECECEC", name: "ImportConfiguration" },
["ini"]: { icon: "", color: "#6d8086", name: "Ini", type: 'ext' },
["java"]: { icon: "", color: "#cc3e44", name: "Java", type: 'ext' },
["jl"]: { icon: "", color: "#a270ba", name: "Jl", type: 'ext' },
["jpeg"]: { icon: "", color: "#a074c4", name: "Jpeg", type: 'ext' },
["jpg"]: { icon: "", color: "#a074c4", name: "Jpg", type: 'ext' },
["js"]: { icon: "", color: "#cbcb41", name: "Js", type: 'ext' },
["json"]: { icon: "", color: "#cbcb41", name: "Json", type: 'ext' },
["jsx"]: { icon: "", color: "#519aba", name: "Jsx", type: 'ext' },
["ksh"]: { icon: "", color: "#4d5a5e", name: "Ksh", type: 'ext' },
["kt"]: { icon: "𝙆", color: "#F88A02", name: "Kotlin", type: 'ext' },
["leex"]: { icon: "", color: "#a074c4", name: "Leex", type: 'ext' },
["less"]: { icon: "", color: "#563d7c", name: "Less", type: 'ext' },
["lhs"]: { icon: "", color: "#a074c4", name: "Lhs", type: 'ext' },
["license.md"]: { icon: "", color: "#cbcb41", name: "License", type: 'file' },
["lua"]: { icon: "", color: "#51a0cf", name: "Lua", type: 'ext' },
["markdown"]: { icon: "", color: "#519aba", name: "Markdown", type: 'ext' },
["material"]: { icon: "", color: "#B83998", name: "Material", type: 'ext' },
["md"]: { icon: "", color: "#519aba", name: "Md", type: 'ext' },
["mdx"]: { icon: "", color: "#519aba", name: "Mdx", type: 'ext' },
['mint'] : { icon : "", color :'#87c095', name : "Mint" },
["mix.lock"]: { icon: "", color: "#a074c4", name: "MixLock", type: 'file' },
["mjs"]: { icon: "", color: "#f1e05a", name: "Mjs", type: 'ext' },
["ml"]: { icon: "λ", color: "#e37933", name: "Ml", type: 'ext' },
["mli"]: { icon: "λ", color: "#e37933", name: "Mli", type: 'ext' },

["mp3"]: { icon: " ", color: "#404bad", name: "mp3", type: 'ext', double: true },
["m4a"]: { icon: " ", color: "#804b4d", name: "m4a", type: 'ext', double: true },
["flac"]: { icon: " ", color: "#408b8d", name: "flac", type: 'ext', double: true },
["wav"]: { icon: " ", color: "#605bfd", name: "wav", type: 'ext', double: true },

["mustache"]: { icon: "", color: "#e37933", name: "Mustache", type: 'ext' },
["nix"]: { icon: "", color: "#7ebae4", name: "Nix", type: 'ext' },
["node_modules"]: { icon: "", color: "#E8274B", name: "NodeModules", type: 'folder' },
["opus"]: { icon: "", color: "#F88A02", name: "OPUS", type: 'ext' },
["otf"]: { icon: "", color: "#ECECEC", name: "OpenTypeFont", type: 'ext' },
["pck"]: { icon: "", color: "#6d8086", name: "PackedResource", type: 'ext' },
["pdf"]: { icon: "", color: "#b30b00", name: "Pdf", type: 'ext' },
["php"]: { icon: "", color: "#a074c4", name: "Php", type: 'ext' },
["pl"]: { icon: "", color: "#519aba", name: "Pl", type: 'ext' },
["pm"]: { icon: "", color: "#519aba", name: "Pm", type: 'ext' },
["png"]: { icon: "", color: "#a074c4", name: "Png", type: 'ext' },
["pp"]: { icon: "", color: "#302B6D", name: "Pp", type: 'ext' },
["ppt"]: { icon: "", color: "#cb4a32", name: "Ppt", type: 'ext' },
["pro"] : { icon : "", color : "#e4b854", name : "Prolog" },
["ps1"]: { icon: "", color: "#4d5a5e", name: "PromptPs1", type: 'ext' },
["psb"]: { icon: "", color: "#519aba", name: "Psb", type: 'ext' },
["psd"]: { icon: "", color: "#519aba", name: "Psd", type: 'ext' },
["py"]: { icon: "", color: "#3572A5", name: "Py", type: 'ext' },
["pyc"]: { icon: "", color: "#519aba", name: "Pyc", type: 'ext' },
["pyd"]: { icon: "", color: "#519aba", name: "Pyd", type: 'ext', },
["pyo"]: { icon: "", color: "#519aba", name: "Pyo", type: 'ext' },
["r"]: { icon: "ﳒ", color: "#358a5b", name: "R", type: 'ext' },
["rake"]: { icon: "", color: "#701516", name: "Rake", type: 'file' },
["rb"]: { icon: "", color: "#701516", name: "Rb", type: 'ext' },
["rlib"]: { icon: "", color: "#dea584", name: "Rlib", type: 'ext' },
["rmd"]: { icon: "", color: "#519aba", name: "Rmd", type: 'ext' },
["rproj"]: { icon: "鉶", color: "#358a5b", name: "Rproj", type: 'ext', double: true },
["rs"]: { icon: "", color: "#dea584", name: "Rs", type: 'ext' },
["rss"]: { icon: "", color: "#FB9D3B", name: "Rss", type: 'ext' },
["sass"]: { icon: "", color: "#f55385", name: "Sass", type: 'ext' },
["scala"]: { icon: "", color: "#cc3e44", name: "Scala", type: 'ext' },
["scss"]: { icon: "", color: "#f55385", name: "Scss", type: 'ext' },
["sh"]: { icon: "", color: "#4d7afe", name: "Sh", type: 'ext' },
["slim"]: { icon: "", color: "#e34c26", name: "Slim", type: 'ext' },
["sln"]: { icon: "", color: "#854CC7", name: "Sln", type: 'ext' },
["sql"]: { icon: "", color: "#dad8d8", name: "Sql", type: 'ext' },
["styl"]: { icon: "", color: "#8dc149", name: "Styl", type: 'ext' },
["suo"]: { icon: "", color: "#854CC7", name: "Suo", type: 'ext' },
["svelte"]: { icon: "", color: "#ff3e00", name: "Svelte", type: 'ext' },
["svg"]: { icon: "ﰟ", color: "#FFB13B", name: "Svg", type: 'ext' },
["swift"]: { icon: "", color: "#e37933", name: "Swift", type: 'ext' },
["t"]: { icon: "", color: "#519aba", name: "Tor", type: 'ext' },
["terminal"]: { icon: "", color: "#31B53E", name: "Terminal", type: 'ext' },
["tex"]: { icon: "ﭨ", color: "#3D6117", name: "Tex", type: 'ext' },
["toml"]: { icon: "", color: "#6d8086", name: "Toml", type: 'ext' },
["tres"]: { icon: "", color: "#cbcb41", name: "TextResource", type: 'ext' },
["ts"]: { icon: "", color: "#519aba", name: "Ts", type: 'ext' },
["tscn"]: { icon: "", color: "#a074c4", name: "TextScene", type: 'ext' },
["tsx"]: { icon: "", color: "#519aba", name: "Tsx", type: 'ext' },
["twig"]: { icon: "", color: "#8dc149", name: "Twig", type: 'ext' },
["vim"]: { icon: "", color: "#019833", name: "Vim", type: 'ext' },
["vue"]: { icon: "﵂", color: "#8dc149", name: "Vue", type: 'ext' },
["webmanifest"]: { icon: "", color: "#f1e05a", name: "Webmanifest", type: 'file' },
["webp"]: { icon: "", color: "#a074c4", name: "Webp", type: 'ext' },
["webpack"]: { icon: "ﰩ", color: "#519aba", name: "Webpack", type: 'folder' },
["xcplayground"]: { icon: "", color: "#e37933", name: "XcPlayground", },
["xls"]: { icon: "", color: "#207245", name: "Xls", type: 'ext' },
["xml"]: { icon: "謹", color: "#e37933", name: "Xml", type: 'ext', double: true },
["xul"]: { icon: "", color: "#e37933", name: "Xul", type: 'ext' },
["yaml"]: { icon: "", color: "#6d8086", name: "Yaml", type: 'ext' },
["yml"]: { icon: "", color: "#6d8086", name: "Yml", type: 'ext' },
["zig"]:  { icon : '', color : '#f69a1b', name : 'Zig', },
["zsh"]: { icon: "", color: "#89e051", name: "Zsh", type: 'ext' },
["sty"]: { icon: "ﭨ", color: "#EE6E73", name: "Tex Style", type: 'ext' },
["tfm"]: { icon: "ﭨ" , color: "#0E5E43", name: "Tex Font Matric", type: 'ext' },
["mf"]: { icon: "" , color: "#4E7Ef3", name: "Metafont", type: 'ext' },
["dic"]: { icon: " "  , color: "#cbcb41", name: "Metafont", type: 'ext', double: true },
["txt"]: { icon: " "  , color: "#407b81", name: "Text file", type: 'ext', double: true },
["Gemfile"]: { icon: " "  , color: "#a03b31", name: "Ruby gemfile", type: 'ext', double: true },
["gz"]: { icon: ""  , color: "#603b81", name: "Gzip", type: 'ext'},
["zip"]: { icon: ""  , color: "#905b61", name: "Zip", type: 'ext'},
};
