#!/bin/zsh

source "core.zsh"

_fzf_complete_docker-images() {
  fzf_options=$1
  _fzf_complete --ansi --tiebreak=index --header-lines=1 ${(Q)${(Z+n+)fzf_options}} -- "$@" < <(
      docker images --format 'table {{.ID}};{{.Repository}};{{.Tag}};{{if .CreatedSince}}{{.CreatedSince}}{{else}}N/A{{end}};{{.Size}}' 2> /dev/null \
    | FS=';' _fzf_complete_tabularize $fg[yellow] $reset_color{,,}
  )
}

_fzf_complete_docker-images_post() {
    awk '{ print $1 }'
}

_fzf_complete_docker-images "$@"
