#!/bin/zsh

source "core.zsh"

_fzf_complete_docker-images-repository() {
  local fzf_options=$1
  shift 1
  _fzf_complete --ansi --tiebreak=index --header-lines=1 ${(Q)${(Z+n+)fzf_options}} -- "$@" < <(
    docker images --filter 'dangling=false' --format 'table {{.Repository}};{{.ID}};{{.Tag}};{{if .CreatedSince}}{{.CreatedSince}}{{else}}N/A{{end}};{{.Size}}' 2> /dev/null \
      | FS=';' _fzf_complete_tabularize $fg[yellow] $reset_color{,,}
  )
}

_fzf_complete_docker-images-repository_post() {
  local input=$(awk '{ print $1 }')
  if [[ -z $input ]]; then
    return
  fi
  echo -n $input
}

_fzf_complete_docker-images-repository "$*"
