#!/bin/zsh

source "core.zsh"

_fzf_complete_docker-networks() {
  local fzf_options=$1
  shift

  _fzf_complete --ansi --tiebreak=index --header-lines=1 ${(Q)${(Z+n+)fzf_options}} -- "$@" < <(
    docker network list --format 'table {{.ID}};{{.Name}};{{.Driver}};{{.Scope}}' 2> /dev/null \
      | FS=';' _fzf_complete_tabularize $fg[yellow] $reset_color{,}
  )
}

_fzf_complete_docker-networks_post() {
  awk '{ print $1 }'
}
_fzf_complete_docker-networks "$*"
