#!/bin/zsh

source "core.zsh"

_fzf_complete_docker-containers() {
  local docker_options=$1
  local fzf_options=$2
  shift 2

  _fzf_complete --ansi --tiebreak=index --header-lines=1 ${(Q)${(Z+n+)fzf_options}} -- "$@" < <(
    docker container list ${(Q)${(Z+n+)docker_options}} \
      --format 'table {{.ID}};{{.Image}};{{.Command}};{{.RunningFor}};{{.Status}};{{.Ports}};{{.Names}}' 2> /dev/null \
        | FS=';' _fzf_complete_tabularize $fg[yellow] $reset_color{,,,,}
  )
}

_fzf_complete_docker-containers_post() {
  local input=$(awk '{ print $1 }')

  if [[ -z $input ]]; then
    return
  fi

  if [[ $subcommand = cp ]]; then
    echo -n $input:
  else
    echo $input
  fi
}
_fzf_complete_docker-containers "$*"
